apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Limboocy/k8s-observability.git'
    targetRevision: staging
    path: manifest
    
    # We keep kustomize here just in case, but the heavy lifting 
    # is now done inside the manifest/kustomization.yaml file itself.
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring-staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # <--- CRITICAL: This builds the room since we removed the file.