apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Limboocy/k8s-observability.git'
    targetRevision: staging
    path: manifest

    # --- ADD THIS BLOCK ---
    kustomize:
      nameSuffix: -staging
      commonLabels:
        environment: staging

    # ----------------------

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true