apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-main   # <--- The New Name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Limboocy/k8s-observability.git'
    targetRevision: main       # <--- Important: Tracks the MAIN branch
    path: manifest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # <--- CRITICAL: This builds the room since we removed the file.