apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: 
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    # alerting:
    #   alertmanagers:
    #     - static_configs:
    #         - targets:
    #           # - alertmanager:9093
          
    # rule_files:
    #   - "alert_rules.yml"  <-- Commented out until we create this file later

  scrape_configs:
      # Job 1: Internal monitoring
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      # Job 2: Multi-Tenant Client Monitoring
      - job_name: "CLIENT_MONITORING"
        # This magic trick ensures Grafana sees the "Alias" as the name, not the IP address
        relabel_configs:
          - source_labels: [alias]
            target_label: instance
            replacement: $1
        
        static_configs:
          # --- TENANT: CRUZCON ---
          - targets: ["100.112.106.118:9182"] 
            labels:
              company: "Cruzcon"
              alias: "Cruzcon-APP"
              role: "Application"
              connection: "magicdns"

          - targets: ["100.102.111.12:9182"] 
            labels:
              company: "Cruzcon"
              alias: "Cruzcon-RD"
              role: "Remote_Desktop"
              connection: "magicdns"

          # --- TENANT: XTI-Laptop ---
          - targets: ["100.76.232.24:9182"] 
            labels:
              company: "XTI"
              alias: "XTI-Laptop"
              role: "Application"
              connection: "magicdns"