apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-prometheus-config.yaml
  - 02-prometheus-deployment.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - vm-alerts-configmap.yaml
  # Add your Grafana files here if you have them, for example:
  # - 03-grafana-datasource.yaml
  # - 04-grafana-deployment.yaml